name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and format check
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy
          pip install homeassistant
      
      - name: Run black
        run: black --check custom_components/
      
      - name: Run isort
        run: isort --check-only custom_components/
      
      - name: Run mypy
        run: mypy custom_components/

  validate:
    runs-on: ubuntu-latest
    name: Validate integration
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install Home Assistant
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
      
      - name: Validate manifest
        run: |
          python -m json.tool custom_components/elro_connects_realtime/manifest.json
      
      - name: Validate strings
        run: |
          python -m json.tool custom_components/elro_connects_realtime/strings.json

  # hacs:
  #   runs-on: ubuntu-latest
  #   name: HACS validation
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4
      
  #     - name: HACS validation
  #       uses: hacs/action@main
  #       with:
  #         category: integration
   